import MenuManagement from "../pages/menumanagement";

const translations = {
    en: {
        headerTiming :"Mon-Sun: 11:00 AM - 10:00 PM",
        FilterText:"Filters",
        SearchText:"Search",
        FooterTitle1: "Hours of Operation",
        FooterTitle2: "Contact Us",
        FooterTitle3: "Connect With Us",
        Date1: "Monday - Friday",
        Date2: "Saturday",
        Date3: "Sunday",
        Timing1: "11:00 AM - 10:00 PM",
        Timing2: "12:00 PM - 11:00 PM",
        Timing3: "12:00 PM - 9:00 PM",
        Phone: "(123) 456-7890",
        Email: "info@restaurant.com",
        Address1: "123 Restaurant Street",
        Address2: "City, State 12345",
        ConnectUsMessage: "Join our mailing list for updates and special offers!",
        EmailPlaceholder: "Enter your email",
        EmailButton: "Subscribe",
        CopyrightTxt: "© 2023 Restaurant Name. All rights reserved.",
        seachPlaceholder:"Search",
        categoryTitle:"Categories",
        sectionTitle: "Appetizers Specials Deals",
        subCategoryTitle: "Subcategories",//
        language:"Language",
        addItem:"Add Item",
        setting:"Setting",
        name:"Name",
        title:"Title",
        description:"Description",
        sku:"SKU",
        price:"Price",
        dietaryOptions:"Dietary Options",
        highlightText:"HighLight text",
        image:"Image",
        submit:"Submit",
        livePreview:"Live Preview",
        existing:"Existing",
        remove:"Remove",
        menuManagement:"Menu Management",
      // Other translatable strings for English
    },
    he: {
        headerTiming:"שני-ראשון: 11:00 - 22:00",
        FilterText:"מסננים",
        SearchText:"לְחַפֵּשׂ",
        FooterTitle1: "שעות פעילות",
        FooterTitle2: "צור קשר",
        FooterTitle3: "התחבר איתנו",
        Date1: "שני - שישי",
        Date2: "שבת",
        Date3: "ראשון",
        Timing1: "11:00 לפנה\"צ - 10:00 בערב",
        Timing2: "12:00 בצהריים - 11:00 בערב",
        Timing3: "12:00 בצהריים - 9:00 בערב",
        Phone: "(123) 456-7890",
        Email: "info@restaurant.com",
        Address1: "רחוב המסעדה 123",
        Address2: "עיר, מדינה 12345",
        ConnectUsMessage: "הצטרף לרשימת הדיוור שלנו לקבלת עדכונים והצעות מיוחדות!",
        EmailPlaceholder: "הזן את הדוא\"ל שלך",
        EmailButton: "הרשם",
        CopyrightTxt: "© 2023 שם המסעדה. כֹּל הַזְכוּיוֹת שְׁמוּרוֹת.",
        seachPlaceholder:"לְחַפֵּשׂ",
        categoryTitle:"קטגוריות",
        sectionTitle: "הצעות מיוחדות של אפטיזר",
        subCategoryTitle: "קטגוריות משנה",
        language: "שפה",
        addItem: "הוסף פריט",
        setting: "הגדרות",
        name: "שם",
        title: "כותרת",
        description: "תיאור",
        sku: "מק\"ט (SKU)",
        price: "מחיר",
        dietaryOptions: "אפשרויות תזונה",
        highlightText: "טקסט מודגש",
        image: "תמונה",
        submit: "שלח",
        livePreview: "תצוגה מקדימה",
        existing: "קיים",
        remove: "הסר",
        menuManagement: "ניהול תפריט"
        // Other translatable strings for Hebrew
    },
  };
  
  export default translations;